spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Parasite2142/spring-microservice-configuration.git
          clone-on-start: true
  application:
    name: config-server

server:
  port: 8888

